-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 16:44:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Matija_Topalovic_2721
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Matija_Topalovic_2721
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Matija_Topalovic_2721` DEFAULT CHARACTER SET utf8 ;
USE `Matija_Topalovic_2721` ;

-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Grad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Grad` (
  `GradID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `PostanskiBroj` VARCHAR(5) NOT NULL,
  `PozivniBroj` VARCHAR(3) NOT NULL,
  `BrojStanovnika` INT NOT NULL,
  `Drava` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GradID`),
  UNIQUE INDEX `GradID_UNIQUE` (`GradID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`VrstaRobe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`VrstaRobe` (
  `VrstaRobeID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Vrsta` VARCHAR(45) NOT NULL,
  `NabavnaCena` INT NOT NULL,
  PRIMARY KEY (`VrstaRobeID`),
  UNIQUE INDEX `VrstaRobeID_UNIQUE` (`VrstaRobeID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Roba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Roba` (
  `RobaID` INT NOT NULL AUTO_INCREMENT,
  `Kolicina` INT NOT NULL,
  `VrstaRobe_VrstaRobeID` INT NOT NULL,
  PRIMARY KEY (`RobaID`),
  UNIQUE INDEX `RobaID_UNIQUE` (`RobaID` ASC) ,
  INDEX `fk_Roba_VrstaRobe1_idx` (`VrstaRobe_VrstaRobeID` ASC) ,
  CONSTRAINT `fk_Roba_VrstaRobe1`
    FOREIGN KEY (`VrstaRobe_VrstaRobeID`)
    REFERENCES `Matija_Topalovic_2721`.`VrstaRobe` (`VrstaRobeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Prodavnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Prodavnica` (
  `ProdavnicaID` INT NOT NULL AUTO_INCREMENT,
  `Adresa` VARCHAR(45) NOT NULL,
  `Naziv` VARCHAR(45) NOT NULL,
  `BrojTelefona` VARCHAR(9) NOT NULL,
  `Grad_GradID` INT NOT NULL,
  PRIMARY KEY (`ProdavnicaID`),
  UNIQUE INDEX `ProdavnicaID_UNIQUE` (`ProdavnicaID` ASC) ,
  INDEX `fk_Prodavnica_Grad_idx` (`Grad_GradID` ASC) ,
  CONSTRAINT `fk_Prodavnica_Grad`
    FOREIGN KEY (`Grad_GradID`)
    REFERENCES `Matija_Topalovic_2721`.`Grad` (`GradID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Magacin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Magacin` (
  `MagacinID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Kapacitet` INT NOT NULL,
  `Prodavnica_ProdavnicaID` INT NOT NULL,
  PRIMARY KEY (`MagacinID`),
  UNIQUE INDEX `MagacinID_UNIQUE` (`MagacinID` ASC) ,
  INDEX `fk_Magacin_Prodavnica1_idx` (`Prodavnica_ProdavnicaID` ASC) ,
  CONSTRAINT `fk_Magacin_Prodavnica1`
    FOREIGN KEY (`Prodavnica_ProdavnicaID`)
    REFERENCES `Matija_Topalovic_2721`.`Prodavnica` (`ProdavnicaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Racunovodstvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Racunovodstvo` (
  `RacunovodstvoID` INT NOT NULL AUTO_INCREMENT,
  `Sektor` INT NOT NULL,
  `BrojTelefona` VARCHAR(9) NOT NULL,
  `Prodavnica_ProdavnicaID` INT NOT NULL,
  PRIMARY KEY (`RacunovodstvoID`),
  UNIQUE INDEX `RacunovodstvoID_UNIQUE` (`RacunovodstvoID` ASC) ,
  INDEX `fk_Racunovodstvo_Prodavnica1_idx` (`Prodavnica_ProdavnicaID` ASC) ,
  CONSTRAINT `fk_Racunovodstvo_Prodavnica1`
    FOREIGN KEY (`Prodavnica_ProdavnicaID`)
    REFERENCES `Matija_Topalovic_2721`.`Prodavnica` (`ProdavnicaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Zaposleni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Zaposleni` (
  `ZaposleniID` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(20) NOT NULL,
  `Prezime` VARCHAR(30) NOT NULL,
  `JMBG` VARCHAR(13) NOT NULL,
  `AdresaStanovanja` VARCHAR(45) NOT NULL,
  `BrojTelefona` VARCHAR(9) NOT NULL,
  `DrugiTelefon` VARCHAR(9) NULL,
  `Plata` INT NOT NULL,
  `Godiste` INT(4) NOT NULL,
  `Grad_GradID` INT NOT NULL,
  PRIMARY KEY (`ZaposleniID`),
  UNIQUE INDEX `ZaposleniID_UNIQUE` (`ZaposleniID` ASC) ,
  INDEX `fk_Zaposleni_Grad1_idx` (`Grad_GradID` ASC) ,
  CONSTRAINT `fk_Zaposleni_Grad1`
    FOREIGN KEY (`Grad_GradID`)
    REFERENCES `Matija_Topalovic_2721`.`Grad` (`GradID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`RadnoMesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`RadnoMesto` (
  `RadnoMestoID` INT NOT NULL AUTO_INCREMENT,
  `NazivRadnogMesta` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`RadnoMestoID`),
  UNIQUE INDEX `RadnoMestoID_UNIQUE` (`RadnoMestoID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Kupac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Kupac` (
  `KupacID` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KupacID`),
  UNIQUE INDEX `KupacID_UNIQUE` (`KupacID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`PodaciORobi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`PodaciORobi` (
  `Magacin_MagacinID` INT NOT NULL,
  `Roba_RobaID` INT NOT NULL,
  `CenaRobe` INT NOT NULL,
  PRIMARY KEY (`Magacin_MagacinID`, `Roba_RobaID`),
  INDEX `fk_Magacin_has_Roba_Roba1_idx` (`Roba_RobaID` ASC) ,
  INDEX `fk_Magacin_has_Roba_Magacin1_idx` (`Magacin_MagacinID` ASC) ,
  UNIQUE INDEX `Magacin_MagacinID_UNIQUE` (`Magacin_MagacinID` ASC) ,
  UNIQUE INDEX `Roba_RobaID_UNIQUE` (`Roba_RobaID` ASC) ,
  CONSTRAINT `fk_Magacin_has_Roba_Magacin1`
    FOREIGN KEY (`Magacin_MagacinID`)
    REFERENCES `Matija_Topalovic_2721`.`Magacin` (`MagacinID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magacin_has_Roba_Roba1`
    FOREIGN KEY (`Roba_RobaID`)
    REFERENCES `Matija_Topalovic_2721`.`Roba` (`RobaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Zaposleni_has_RadnoMesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Zaposleni_has_RadnoMesto` (
  `Zaposleni_ZaposleniID` INT NOT NULL,
  `RadnoMesto_RadnoMestoID` INT NOT NULL,
  `Prodavnica_ProdavnicaID` INT NOT NULL,
  PRIMARY KEY (`Zaposleni_ZaposleniID`, `RadnoMesto_RadnoMestoID`, `Prodavnica_ProdavnicaID`),
  INDEX `fk_Zaposleni_has_RadnoMesto_RadnoMesto1_idx` (`RadnoMesto_RadnoMestoID` ASC) ,
  INDEX `fk_Zaposleni_has_RadnoMesto_Zaposleni1_idx` (`Zaposleni_ZaposleniID` ASC) ,
  INDEX `fk_Zaposleni_has_RadnoMesto_Prodavnica1_idx` (`Prodavnica_ProdavnicaID` ASC) ,
  CONSTRAINT `fk_Zaposleni_has_RadnoMesto_Zaposleni1`
    FOREIGN KEY (`Zaposleni_ZaposleniID`)
    REFERENCES `Matija_Topalovic_2721`.`Zaposleni` (`ZaposleniID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaposleni_has_RadnoMesto_RadnoMesto1`
    FOREIGN KEY (`RadnoMesto_RadnoMestoID`)
    REFERENCES `Matija_Topalovic_2721`.`RadnoMesto` (`RadnoMestoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaposleni_has_RadnoMesto_Prodavnica1`
    FOREIGN KEY (`Prodavnica_ProdavnicaID`)
    REFERENCES `Matija_Topalovic_2721`.`Prodavnica` (`ProdavnicaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Cenovnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Cenovnik` (
  `CenovnikID` INT NOT NULL AUTO_INCREMENT,
  `DatumOdKogVazi` DATE NOT NULL,
  `Prodavnica_ProdavnicaID` INT NOT NULL,
  PRIMARY KEY (`CenovnikID`),
  UNIQUE INDEX `CenovnikID_UNIQUE` (`CenovnikID` ASC) ,
  INDEX `fk_Cenovnik_Prodavnica1_idx` (`Prodavnica_ProdavnicaID` ASC) ,
  CONSTRAINT `fk_Cenovnik_Prodavnica1`
    FOREIGN KEY (`Prodavnica_ProdavnicaID`)
    REFERENCES `Matija_Topalovic_2721`.`Prodavnica` (`ProdavnicaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`ArtikalCenovnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`ArtikalCenovnika` (
  `Cenovnik_CenovnikID` INT NOT NULL,
  `Roba_RobaID` INT NOT NULL,
  `CenaArtikla` INT NOT NULL,
  PRIMARY KEY (`Cenovnik_CenovnikID`, `Roba_RobaID`),
  INDEX `fk_Cenovnik_has_Roba_Roba1_idx` (`Roba_RobaID` ASC) ,
  INDEX `fk_Cenovnik_has_Roba_Cenovnik1_idx` (`Cenovnik_CenovnikID` ASC) ,
  CONSTRAINT `fk_Cenovnik_has_Roba_Cenovnik1`
    FOREIGN KEY (`Cenovnik_CenovnikID`)
    REFERENCES `Matija_Topalovic_2721`.`Cenovnik` (`CenovnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cenovnik_has_Roba_Roba1`
    FOREIGN KEY (`Roba_RobaID`)
    REFERENCES `Matija_Topalovic_2721`.`Roba` (`RobaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`Racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`Racun` (
  `RacunID` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATE NOT NULL,
  `Vreme` TIME NOT NULL,
  `PDV` INT NOT NULL,
  `KodRacuna` INT(10) NOT NULL,
  `Zaposleni_ZaposleniID` INT NOT NULL,
  `Kupac_KupacID` INT NOT NULL,
  `Racunovodstvo_RacunovodstvoID` INT NOT NULL,
  PRIMARY KEY (`RacunID`),
  UNIQUE INDEX `RacunID_UNIQUE` (`RacunID` ASC) ,
  INDEX `fk_Racun_Zaposleni1_idx` (`Zaposleni_ZaposleniID` ASC) ,
  INDEX `fk_Racun_Kupac1_idx` (`Kupac_KupacID` ASC) ,
  INDEX `fk_Racun_Racunovodstvo1_idx` (`Racunovodstvo_RacunovodstvoID` ASC) ,
  CONSTRAINT `fk_Racun_Zaposleni1`
    FOREIGN KEY (`Zaposleni_ZaposleniID`)
    REFERENCES `Matija_Topalovic_2721`.`Zaposleni` (`ZaposleniID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Racun_Kupac1`
    FOREIGN KEY (`Kupac_KupacID`)
    REFERENCES `Matija_Topalovic_2721`.`Kupac` (`KupacID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Racun_Racunovodstvo1`
    FOREIGN KEY (`Racunovodstvo_RacunovodstvoID`)
    REFERENCES `Matija_Topalovic_2721`.`Racunovodstvo` (`RacunovodstvoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matija_Topalovic_2721`.`ArtikalRacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matija_Topalovic_2721`.`ArtikalRacuna` (
  `Racun_RacunID` INT NOT NULL,
  `ArtikalCenovnika_Cenovnik_CenovnikID` INT NOT NULL,
  `ArtikalCenovnika_Roba_RobaID` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  PRIMARY KEY (`Racun_RacunID`, `ArtikalCenovnika_Cenovnik_CenovnikID`, `ArtikalCenovnika_Roba_RobaID`),
  INDEX `fk_Racun_has_ArtikalCenovnika_ArtikalCenovnika1_idx` (`ArtikalCenovnika_Cenovnik_CenovnikID` ASC, `ArtikalCenovnika_Roba_RobaID` ASC) ,
  INDEX `fk_Racun_has_ArtikalCenovnika_Racun1_idx` (`Racun_RacunID` ASC) ,
  CONSTRAINT `fk_Racun_has_ArtikalCenovnika_Racun1`
    FOREIGN KEY (`Racun_RacunID`)
    REFERENCES `Matija_Topalovic_2721`.`Racun` (`RacunID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Racun_has_ArtikalCenovnika_ArtikalCenovnika1`
    FOREIGN KEY (`ArtikalCenovnika_Cenovnik_CenovnikID` , `ArtikalCenovnika_Roba_RobaID`)
    REFERENCES `Matija_Topalovic_2721`.`ArtikalCenovnika` (`Cenovnik_CenovnikID` , `Roba_RobaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
